export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS"
export const ADD_PRODUCT_TO_BASKET = "ADD_PRODUCT_TO_BASKET"
export const INCREMENT_BASKET_PRODUCT = "INCREMENT_BASKET_PRODUCT"
export const EMPTY_BASKET = "EMPTY_BASKET"
